"attached_disks":
- "cache": "none"
  "datastore_id": "local-hdd"
  "discard": ""
  "file_format": "qcow2"
  "file_id": ""
  "interface": "scsi0"
  "iothread": true
  "label": "ssh_keys"
  "mountpoint": "/var/lib/ansible"
  "path_in_datastore": "94000001/vm-94000001-disk-0.qcow2"
  "read_only": true
  "size": 1
  "speed": []
  "ssd": false
"vmid": 94000001
