"attached_disks":
- "aio": "io_uring"
  "backup": true
  "cache": "none"
  "datastore_id": "main-vms"
  "discard": "ignore"
  "file_format": "raw"
  "file_id": ""
  "interface": "scsi0"
  "iothread": true
  "label": null
  "mountpoint": "/var/lib/ansible"
  "path_in_datastore": "vm-103-disk-0"
  "read_only": false
  "replicate": true
  "serial": ""
  "size": 1
  "speed": []
  "ssd": true
"vmid": "103"
