"attached_disks":
- "aio": "io_uring"
  "backup": true
  "cache": "none"
  "datastore_id": "local-nvme"
  "discard": "ignore"
  "file_format": "raw"
  "file_id": ""
  "interface": "scsi0"
  "iothread": true
  "label": null
  "mountpoint": "/var/lib/backup"
  "path_in_datastore": "vm-109-disk-0"
  "read_only": null
  "replicate": true
  "serial": ""
  "size": 50
  "speed": []
  "ssd": true
- "aio": "io_uring"
  "backup": true
  "cache": "none"
  "datastore_id": "local-nvme"
  "discard": "ignore"
  "file_format": "raw"
  "file_id": ""
  "interface": "scsi1"
  "iothread": true
  "label": null
  "mountpoint": "/var/lib/docker"
  "path_in_datastore": "vm-109-disk-1"
  "read_only": null
  "replicate": true
  "serial": ""
  "size": 100
  "speed": []
  "ssd": true
"vmid": "109"
