"attached_disks":
- "aio": "io_uring"
  "backup": true
  "cache": "none"
  "datastore_id": "local-nvme"
  "discard": "ignore"
  "file_format": "raw"
  "file_id": ""
  "interface": "scsi0"
  "iothread": true
  "label": null
  "mountpoint": "/var/lib/backup"
  "path_in_datastore": "vm-104-disk-0"
  "read_only": null
  "replicate": true
  "serial": ""
  "size": 125
  "speed": []
  "ssd": true
- "aio": "io_uring"
  "backup": true
  "cache": "none"
  "datastore_id": "local-nvme"
  "discard": "ignore"
  "file_format": "raw"
  "file_id": ""
  "interface": "scsi1"
  "iothread": true
  "label": null
  "mountpoint": "/var/lib/nextcloud"
  "path_in_datastore": "vm-104-disk-1"
  "read_only": null
  "replicate": true
  "serial": ""
  "size": 250
  "speed": []
  "ssd": true
- "aio": "io_uring"
  "backup": true
  "cache": "none"
  "datastore_id": "local-nvme"
  "discard": "ignore"
  "file_format": "raw"
  "file_id": ""
  "interface": "scsi2"
  "iothread": true
  "label": null
  "mountpoint": "/var/lib/mysql"
  "path_in_datastore": "vm-104-disk-2"
  "read_only": null
  "replicate": true
  "serial": ""
  "size": 10
  "speed": []
  "ssd": true
"vmid": "104"
