"attached_disks":
- "aio": "io_uring"
  "backup": true
  "cache": "none"
  "datastore_id": "local-hdd"
  "discard": "ignore"
  "file_format": "qcow2"
  "file_id": ""
  "interface": "scsi0"
  "iothread": true
  "label": null
  "mountpoint": "/var/lib/postgresql"
  "path_in_datastore": "112/vm-112-disk-0.qcow2"
  "read_only": null
  "replicate": true
  "serial": ""
  "size": 20
  "speed": []
  "ssd": false
"vmid": "112"
